In [49]:
import numpy as np
import pandas as pd

### 1

In [88]:
Numpy = np.array([[ 1, 2, 3, 3, 1], [ 6, 8, 11, 10, 7]])
Numpy = Numpy.transpose()
Numpy

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [92]:
mean_a = np.mean(Numpy, axis = 0)
mean_a


array([2. , 8.4])

### 2

In [91]:
a = Numpy.copy()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [93]:


a_centered = np.subtract(a, np.matrix(mean_a))
a_centered



matrix([[-1. , -2.4],
        [ 0. , -0.4],
        [ 1. ,  2.6],
        [ 1. ,  1.6],
        [-1. , -1.4]])

### 3

In [103]:
x = np.dot(a_centered[:, 1], np.transpose(a_centered[:, 0]))
x


matrix([[ 2.4, -0. , -2.4, -2.4,  2.4],
        [ 0.4, -0. , -0.4, -0.4,  0.4],
        [-2.6,  0. ,  2.6,  2.6, -2.6],
        [-1.6,  0. ,  1.6,  1.6, -1.6],
        [ 1.4, -0. , -1.4, -1.4,  1.4]])